name: 'QMS Integrity check'
description: 'Checks the files cheked in for existence of required tags'
inputs:
  feature_files_dir:
    required: true
    description: 'The directory where the feature files are located'
    default: '.'
  doc_files_dir:
    required: true
    description: 'The directory where the documentation files are located'
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        pip install behave
      shell: bash
    - name: show files
      run: |
        echo "Feature files are located at ${{ inputs.feature_files_dir }}"
        echo "Documentation files are located at ${{ inputs.doc_files_dir }}"
        ls -l ${{ github.workspace }}
        ls -l && echo "^^^"
        echo $(pwd) && echo "<---"
        echo "^^^"

      shell: bash
    - name: Run integrity check
      run: |
        echo "Running integrity check"
        python3 ${{ github.workspace }} src/main.py ${{ inputs.feature_files_dir }} ${{ inputs.doc_files_dir }}
      shell: bash
